### ISSUE TITLE
Sending imaging data correctly

### ISSUE THREAD

**Issue by zachkinstner** [OSVR/OSVR-Leap-Motion#1]
Using the `Imaging_cpp.exe` testing app (provided in OSVR Core), we can test the imaging data provided to the `/camera` path. With the current code, the testing app shows the expected image output only when the code _also_ outputs some sample data via `std::cout`.

The lines to un-comment are [this one](https://github.com/OSVR/OSVR-Leap-Motion/blob/9eaa5075a393053d2dcbf1cb29604e63837169f9/Imaging.cpp#L59) and [this one](https://github.com/OSVR/OSVR-Leap-Motion/blob/9eaa5075a393053d2dcbf1cb29604e63837169f9/Imaging.cpp#L62) in `Imaging.cpp`. Without these lines, the testing app only shows a gray box (with correct dimensions). With these lines, the testing app shows the expected image data. If `flush` is also included in the output, I get the gray box result, so perhaps the output code is forcing the image data to stick around long enough for the testing app to access it.

I tried several variations with the buffers, but the "gray box" issue seems to be the same regardless of the approach. Any ideas? Examples of correct imaging interface usage?

**Comment by zachkinstner** [comment]
The docs for [`osvrDeviceImagingReportFrame()`](http://resource.osvr.com/internal-docs/OSVR-Core-Implementation/group__PluginKitCImaging.html#gaf0341ddcf3c2ec9d8dc6de0d59b0b79a) say:

> `imageData`: A pointer to a copy of the image data, will be destroyed when no longer needed using OpenCV deallocation functions.

**Comment by zachkinstner** [comment]
I also wonder if it can/should work to cast `Leap.Image.data()` as `OSVR_ImageBufferElement*` and provide it as the `imageData` parameter, rather than copying this data into a separate buffer. ([`OSVR_ImageBufferElement`](http://resource.osvr.com/internal-docs/OSVR-Core-Implementation/group__ClientKit.html) is a typedef for `unsigned char`.)

**Comment by jdonald** [comment]
> perhaps the output code is forcing the image data to stick around long enough for the testing app to access it.

Indeed it could be timing related. An <tt>img.data()</tt> raw pointer should stick around as long as a copy of that <tt>Image</tt> object is around. Note that the <tt>Leap::Image</tt> type is a shared_ptr under the hood.

> I also wonder if it can/should work to cast Leap.Image.data() as OSVR_ImageBufferElement\* and provide it as the imageData parameter, rather than copying this data into a separate buffer. 

Because they say "will be destroyed when no longer needed using OpenCV deallocation functions" I don't think this would work. One should not attempt to delete the Leap API image pointers. For now I think we need to do a copy. Of course, once we have something running and measure its performance, we may find a latency bottleneck and have to reconsider some way to avoid the copy.

**Comment by zachkinstner** [comment]
When I limit the dimensions of the image sent by the plugin, I can avoid the "gray box" issue. For example, I can send a 240x240 image (instead of the full 640x240), with no `std::cout` output, and see an image result in `Imaging_cpp.exe`. The 240x240 size worked for me, but a 256x256 size resulted in the "gray box".

The "gray box" issue might be a bug/limitation with the `Imaging_cpp.exe` testing app itself. I noticed that, when there is a "gray box" result, the image window actually freezes up. It uses a "wait" cursor and shows "(Not Responding)" in the title bar. For some reason, this freeze doesn't occur when I include the `std::cout` output in the plugin code (the image displays as expected).

@jdonald, who should we ask at OSVR about this particular issue? Based on my findings today, I think we can assume that the image data is being sent from the plugin successfully, even if the "gray box" issue occurs. Initially, I was thinking that "gray box" meant "no data recieved".

**Comment by jdonald** [comment]
> @jdonald, who should we ask at OSVR about this particular issue?

@rpavlik

**Comment by rpavlik** [comment]
Hmm, that is interesting. I'd have to look through the code behind the imaging interface again, but I'm guessing it's related to the fact that the Imager interface assumes you'll be providing data using OpenCV. Instead of using the contents of https://github.com/OSVR/OSVR-Leap-Motion/blob/9eaa5075a393053d2dcbf1cb29604e63837169f9/Imaging.cpp#L38 and the osvrDeviceImagingReportFrame method directly, could you create an OpenCV `cv::Mat` for your existing data and pass that to the C++ imaging wrapper?

**Comment by zachkinstner** [comment]
Hi @rpavlik, I can give this a try. I wasn't aware of the C++ wrapper details -- that [docs page](http://resource.osvr.com/docs/OSVR-Core/group__PluginKitCppImaging.html) is empty. However, I found [`ImagingInterface.h`](https://github.com/OSVR/OSVR-Core/blob/master/inc/osvr/PluginKit/ImagingInterface.h), so I should be able to work from that.

**Comment by rpavlik** [comment]
Thanks for pointing out that empty page. I figured people would start from the example, which uses C++. I've filed an issue over there. https://github.com/OSVR/OSVR-Core/issues/178

**Comment by zachkinstner** [comment]
Thanks for your help! Can you post the link to that example?

**Comment by rpavlik** [comment]
Ah - good catch - I didn't put one in the example directory, there's just the stock OpenCV one. Another issue :) https://github.com/OSVR/OSVR-Core/blob/master/plugins/opencv/com_osvr_VideoCapture_OpenCV.cpp

**Comment by rpavlik** [comment]
(filed issue https://github.com/OSVR/OSVR-Core/issues/179 )

**Comment by zachkinstner** [comment]
I was having trouble getting OpenCV to work in VS2013, getting compiler errors like these:

```
...\opencv-3.0.0\build\include\opencv2/core/core_c.h(97) : error C2143 : syntax error : missing ';' before '*'
...\opencv-3.0.0\build\include\opencv2/core/core_c.h(97) : error C4430 : missing type specifier - int assumed.Note : C++ does not support default-int
...\opencv-3.0.0\build\include\opencv2/core/core_c.h(97) : error C2065 : 'CvSize' : undeclared identifier
...\opencv-3.0.0\build\include\opencv2/core/core_c.h(97) : error C2146 : syntax error : missing ')' before identifier 'size'
...\opencv-3.0.0\build\include\opencv2/core/core_c.h(97) : warning C4229 : anachronism used : modifiers on data are ignored
...\opencv-3.0.0\build\include\opencv2/core/core_c.h(97) : error C2059 : syntax error : ')'
...\opencv-3.0.0\build\include\opencv2/core/core_c.h(109) : error C2143 : syntax error : missing ';' before '*'
...\opencv-3.0.0\build\include\opencv2/core/core_c.h(109) : error C4430 : missing type specifier - int assumed.Note : C++ does not support default-int
...\opencv-3.0.0\build\include\opencv2/core/core_c.h(109) : error C2065 : 'image' : undeclared identifier
...\opencv-3.0.0\build\include\opencv2/core/core_c.h(109) : error C2065 : 'CvSize' : undeclared identifier
...\opencv-3.0.0\build\include\opencv2/core/core_c.h(109) : error C2146 : syntax error : missing ')' before identifier 'size'
```

After lots of trial-and-error, I found that these error messages go away if I add this line:

``` cpp
#include <opencv2/core/core_c.h>
```

...before this line:

``` cpp
#include <osvr/PluginKit/ImagingInterface.h>
```

I'm not sure why this happens -- maybe I'm doing something wrong with my OpenCV setup. In any case, I should be able to move on with Ryan's suggestion now.

**Comment by rpavlik** [comment]
We haven't built the core with OpenCV 3.0 yet, and they did a few things including shuffling the includes. I think using 3.0 will mean you'll have to ship those dlls in addition instead of sharing the 2.4.10 (I think) dlls we have in the core now.

**Comment by zachkinstner** [comment]
Ah, that was the issue -- using the wrong OpenCV version. Everything went more smoothly once I switched to version 2.4.10. Thanks!

I have updated the plugin to send the camera and distortion images via the C++ API and `cv::Mat`. As @rpavlik suggested, this resolved the "gray box" issues described above.
