### ISSUE TITLE
Use of TimeValue in C++ code not passing it to the API

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Leap-Motion#12]
Per the docs, use of `OSVR_TimeValue` is only for interoperation with struct timeval and C code. C++ code that isn't passing the results in where such a struct is required is recommended to use the `std::chrono` functionality of C++11.

https://github.com/OSVR/OSVR-Leap-Motion/blob/master/Imaging.cpp#L31

**Comment by zachkinstner** [comment]
Updated to use `std::chrono` (see commit referenced above).

In this scenario, the `Imaging` class is watching the time since the "distortion" image was last sent to OSVR. After an arbitrary duration (currently 2 seconds), the image is sent again.
