### ISSUE TITLE
Not Sure if Hardware Detection is returning True or False

### ISSUE THREAD

**Issue by CJRobertson** [OSVR/OSVR-Leap-Motion#16]
I'm trying to get a Leap Motion controller connected to the OSVR and noticed I had to make my own server config file for the OSVR_Server to know what to do with the 'com' file. When using the server config file I made I get the output that you see in the JSON_Test.jpg which I'm not too sure if its meaning it connected to the controller (none of the IR lights in the controller are on though). Is there something wrong with the plugin or did I do something wrong in the server config setup? I noticed the 'Issue' reported by zachkinstner and saw his solution was implemented but I'm not sure if I'm seeing his results.

![json_test](https://cloud.githubusercontent.com/assets/13307644/11763375/278cab7e-a0bd-11e5-8102-f82d3cb29595.JPG)
![json_screenshot](https://cloud.githubusercontent.com/assets/13307644/11763376/27906ab6-a0bd-11e5-993b-4d50e7b1f992.JPG)

**Comment by CJRobertson** [comment]
I unplugged the Leap Motion controller and the same exact output in the server command window is displayed as well.

**Comment by jdonald** [comment]
> (none of the IR lights in the controller are on though)

The plugin doesn't have control of whether the LEDs are turned on though. That's handled by the service. Have you confirmed that the Leap Motion service is running? That is, is there a green tray icon for the Leap Motion Control Panel, and can it track your hands if you open up the Diagnostic Visualizer?

There may be other problems downstream, but if the Leap Motion controller is not streaming, then the plugin surely wouldn't work.
