### ISSUE TITLE
Sending calibration data via imaging interface

### ISSUE THREAD

**Issue by zachkinstner** [OSVR/OSVR-Leap-Motion#2]
From the [notes for Leap Motion](https://github.com/OSVR/OSVR-Specs-and-Proposals/blob/master/Device%20Integration%20Proposals/Leap%20Motion/Leap%20Motion.md#interface-classes) at the "Specs and Proposals" project:

> one would be a 64x64 (or dynamically based on your API) two-channel 32-bit float frame containing the calibration data

Are we going to include this calibration data?

**Comment by jdonald** [comment]
Absolutely! That was clear at the time from our discussions with Sensics.

I'm not sure how far they got on naming the path tree or other specifications for this data, but it must be provided on some interface.

**Comment by zachkinstner** [comment]
Some relevant notes: [camera images](https://developer.leapmotion.com/documentation/cpp/devguide/Leap_Images.html#get-the-calibration-map) article, [`Image.distortion()`](https://developer.leapmotion.com/documentation/cpp/api/Leap.Image.html#cppclass_leap_1_1_image_1a4c6fa722eba7018e148b13677c7ce609) docs.

See initial solution in the latest commit: [`sendCalibrationImage()`](https://github.com/OSVR/OSVR-Leap-Motion/blob/6ed03878bfe5c2f8f541d197ba387516a6d411b3/Imaging.cpp#L66). This produces images that look like this:

| Left | Right |
| --- | --- |
| ![Left Calibration](http://www.aestheticinteractive.com/clients/leap/osvr/LeapCalibrationLeft.png) | ![Right Calibration](http://www.aestheticinteractive.com/clients/leap/osvr/LeapCalibrationRight.png) |

**Comment by zachkinstner** [comment]
The solution shown above may not be ideal, let's discuss.

---

A) The distortion data uses `float` values, where anything outside of the range [0, 1] is to be ignored. The output images above set the out-of-range values to 0. Values within [0, 1] are transformed to the range [1, 255] for the output image. Is this [1, 255] range sufficient?

If we need a wider range, I'll need some guidance for sending the data. The image "type" could use `OSVR_ImagingValueType::OSVR_IVT_FLOATING_POINT`, and the "depth" could use 4 (bytes). In that scenario, however, I'm not sure how to correctly fill the `char` output buffer using `float` values.

---

B) The distortion data places X and Y values next to each other in the array. The output above rearranges these values so that X is on the top half, and Y is on the bottom half. This makes it easier to verify that the image output is correct. Should we keep the original arrangement of values instead? 

Alternatively, we could split these into 4 separate images.

**Comment by jdonald** [comment]
> A) Is this [1, 255] range sufficient?

I don't think so. We have found that 16-bit floating point (vs 32-bit floating point) is sufficient, but going down to 8-bit precision would probably introduce visible artifacts.

> B) The distortion data places X and Y values next to each other in the array... Should we keep the original arrangement of values instead?

For debugging the separation is useful, but ultimately for an API and reference shaders in Unity ShaderLab or GLSL the values should remain together. By keeping both distortion values in a single RG texture, we avoid an additional texture lookup.

**Comment by zachkinstner** [comment]
> We have found that 16-bit floating point (vs 32-bit floating point) is sufficient

Sounds good, I'll give this a shot.

> the values should remain together

Not a problem, the only change will be to make the use same index (instead of mapping to the top/bottom indexing) when making the image copy.

**Comment by zachkinstner** [comment]
New distortion image results:

| Left | Right |
| --- | --- |
| ![Left Calibration](http://www.aestheticinteractive.com/clients/leap/osvr/LeapCalibrationLeft2.png) | ![Right Calibration](http://www.aestheticinteractive.com/clients/leap/osvr/LeapCalibrationRight2.png) |

I get an error message when trying to use just two channels (RG), so these images use three (RGB). The images use 16-bit values (spread across two `char` buffer cells) instead of the previous 8-bit values.

This approach leaves empty/unused space in the third channel of the data buffer. An alternative approach (currently commented-out in the code) is to use a one-channel image, but double the height (or width) dimension. I'm not sure which format is best on the receiving end -- please advise.

**Comment by jdonald** [comment]
Is that a limitation of some OSVR-texture? In OpenGL I recall we use a two-channel texture for the distortion map: https://github.com/leapmotion-examples/VRIntro

**Comment by russell-taylor** [comment]
You should be able to send floating-point images without converting them to integers at all.

**Comment by zachkinstner** [comment]
> Is that a limitation of some OSVR-texture?

When I use two channels, the `Imaging_cpp.exe` testing app shows the following error message, then immediately freezes up:

```
OpenCV Error: Bad number of channels (Source image must have 1, 3, or 4 channels) in cvConvertImage, file C:\builds\2_4_PackSlave-win32-vc12-shared\opencv\modules\highgui\src\utils.cpp, line 611
```

**Comment by zachkinstner** [comment]
New distortion image results:

| Left | Right |
| --- | --- |
| ![Left Calibration](http://www.aestheticinteractive.com/clients/leap/osvr/LeapCalibrationLeft3.png) | ![Right Calibration](http://www.aestheticinteractive.com/clients/leap/osvr/LeapCalibrationRight3.png) |

These images are sent as 32-bit floating point values, with three channels.

I used `reinterpret_cast<OSVR_ImageBufferElement*>(imageCopy)` to convert the floating-point image data into the `char` buffer. Please let me know if there is a better/preferred way to do this.

**Comment by jdonald** [comment]
I couldn't find any documentation for cvConvertImage(), rather I just came across advice to use Mat::convertTo() instead. Oh well, disallowing two channels just seems like an OpenCV limitation. We can work around that for now. The distortion map generation code can afford not to be super-optimized as it won't be run on every frame, rather only when a new Leap Motion device is attached.

The earlier distortion map looked correct but this recent one is harder to read. It looks like you're now copying a value over to the third channel. I would recommend just setting that to black for clarity.

> I used reinterpret_cast<OSVR_ImageBufferElement*>(imageCopy) to convert the floating-point image data into the char buffer. Please let me know if there is a better/preferred way to do this.

This seems fine to me.

**Comment by zachkinstner** [comment]
> The distortion map generation code can afford not to be super-optimized as it won't be run on every frame, rather only when a new Leap Motion device is attached.

Currently, this data is being sent with each frame/update of the plugin. I'm not sure what would happen if we only sent it once (i.e. on the first frame). The image data may get destroyed after the frame/update cycle is complete. I can try it out with the testing app.

> It looks like you're now copying a value over to the third channel.

Hmm, I don't think so. These images are showing only green and blue, which combine to cyan where overlapping. The third channel would be red (which might combine to create yellow, purple, white, etc).

The visible difference with this vs. the previous images is that it doesn't ignore values that fall outside of the [0, 1] range. For the image display shown here, I assume that values `< 0` become 0 (black) and values `> 1` become 255 (full color).  When reading the actual floating point values, I'd assume that those values will not be truncated, remaining in their full original range (something like [-1, 2]).

**Comment by zachkinstner** [comment]
> I'm not sure what would happen if we only sent it once (i.e. on the first frame).

When I only send the calibration images on the first frame, the `Imaging_cpp.exe` app only shows a (non-frozen) gray box. I assume this means that no image data is available.

I also tried a test where the image data is only sent every X seconds. The image data is not available between those X-second gaps.

So, I think A) we will need to send the data more than once (possibly less frequently than per-frame), and B) an app would need to listen for and consume that data during the same frame that the plugin sends it.

**Comment by jdonald** [comment]
I see. We can cache on our end to avoid calling this part of the Leap API every frame, but may have to always send it on the OSVR side.

That may be acceptable as well, given the the distortion map is much smaller than the images sent every frame.

> The visible difference with this vs. the previous images is that it doesn't ignore values that fall outside of the [0, 1] range.

Okay, that makes sense!

**Comment by zachkinstner** [comment]
> We can cache on our end to avoid calling this part of the Leap API every frame

Do you mean caching it within the Leap API, or caching it within the plugin? If cached within the plugin, is it correct to simply keep the first `Leap::Image::distortion()` result for each left/right camera? 

I think we would still need to create a copy of the cached data each time we send it, since OSVR destroys the copy when it's done using it.

**Comment by jdonald** [comment]
I meant caching within the plugin. Yes, you can simply retain the distortion() values, which are valid until an onDeviceChange() event is seen.

Oh yeah, that's unfortunate that OSVR deletes the pointer you pass each time.

**Comment by rpavlik** [comment]
The purpose behind the deleting the pointer is that OSVR takes ownership of the buffer you pass in. We may keep the buffer around internally to handle analysis plugins, etc. We try to minimize copies and allocations internally.

You shouldn't have to re-send the distortion map every frame, though sending it periodically is probably a good idea until there is a state-retaining version of the imaging interface. https://github.com/OSVR/OSVR-Core/issues/180

As with the previous issue, I'd suggest constructing a cv::Mat object/header for your buffer rather than manually setting those parameters - there is C++ code that can auto-set those much more safely.

**Comment by zachkinstner** [comment]
The left/right distortion data is now cached within two `cv::Mat` matrices. The plugin provides a `clone()` of each matrix to OSVR, and currently sends the data every frame.

**Comment by zachkinstner** [comment]
> sending it periodically is probably a good idea until there is a state-retaining version of the imaging interface

With this latest commit, the distortion images are only sent once every two seconds. I think we can close this issue for now, and revisit it once that  "state-retaining" interface is available.
